version: '3'

services:
  # can be acessed via http://proxy on this network
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 9020:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
  bot:
    build: bot
    restart: always
    environment:
      APPNAME: Admin
      # flag is stored in http://proxy/
      APPURL: http://proxy/
      # regex to sanitize user input
      APPURLREGEX: ^http(|s)://.*$
      # the flag is different on remote
      APPFLAG: gemastik{s3lamat_anda_m3ndap4tkan_XSS}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
    # uncoment this if you need to run the bot in GUI mode
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  # internal network
  internal:
