version: '3'

services:
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 9012:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
  bot:
    build: bot
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://proxy/
      APPURLREGEX: ^http(|s)://.*$
      APPFLAG: gemastik{S3l4m4t_anda_t3lah_m3nj4d1_r4j4_karbit}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
    # uncoment this if you need to run the bot in GUI mode
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  internal:
